version: "3.4"

services:
  iptv-app:
    build:
      context: ./app
    depends_on:
      - iptv-app-mongo
    ports:
      - 32400:3000
    volumes:
      - ./app:/code
    command: [ "npm", "run", "dev" ]

  iptv-app-mongo:
    image: mongo:5.0.3
    ports:
      - 27018:27017

networks:
  default:
    driver: bridge
