version: "3.4"

services:
  iptv-app:
    build:
      context: ./
      target: develop
    depends_on:
      - iptv-app-mongo
    ports:
      - 32300:3000
    volumes:
      - ./:/code
    command: [ "sh", "/code/startup.sh" ]

  iptv-app-mongo:
    image: mongo:5.0.3
    ports:
      - 27018:27017

networks:
  default:
    driver: bridge
